stages:
  - verify
  - plan
  - apply

verify:
  stage: verify
  script:
    - kubectl --help
    - aws --version
    - vault --version
    - terraform --version
    - helm --help

terraform-plan:
  stage: plan
  before_script:
    - >
      echo $TF_ADDRESS

      terraform init \
        -backend-config="address=$TF_ADDRESS" \
        -backend-config="lock_address=$TF_ADDRESS/lock" \
        -backend-config="unlock_address=$TF_ADDRESS/lock" \
        -backend-config="username=$TF_USERNAME" \
        -backend-config="password=$TF_PASSWORD" \
        -backend-config="lock_method=POST" \
        -backend-config="unlock_method=DELETE" \
        -backend-config="retry_wait_min=5"
  script:
    - terraform plan

terraform-apply:
  stage: apply
  before_script:
    - >
      terraform init \
        -backend-config="address=$TF_ADDRESS" \
        -backend-config="lock_address=$TF_ADDRESS/lock" \
        -backend-config="unlock_address=$TF_ADDRESS/lock" \
        -backend-config="username=$TF_USERNAME" \
        -backend-config="password=$TF_PASSWORD" \
        -backend-config="lock_method=POST" \
        -backend-config="unlock_method=DELETE" \
        -backend-config="retry_wait_min=5"
  script:
    - terraform apply -auto-approve